title: "素爱力酥"
url: "https://suailisu.github.io"
baseurl: ""


# blog
permalink: /blog/:categories/:year/:title/
display_categories: [忆旧游, 掷金钱, 好时光, 叨叨令, 寿南山]

# 集合配置
collections:
  screen:            
    output: true     
    permalink: /screen/:title/
  reading:
    output: true
    permalink: /reading/:title/
  games:
    output: true
    permalink: /games/:title/
  moments:
    output: true
    permalink: /moments/:title/

# 目录包含
include:
  - _pages
  - _posts

# 默认设置
defaults:
  - scope:
      path: ""
      type: "screen"
    values:
      layout: "screen-review"

giscus:
  repo: suailisu/suailisu.github.io
  repo_id: R_kgDOQzPkfA
  category: General
  category_id: DIC_kwDOQzPkfM4C0jAt 
  mapping: specific
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: zh-CN

plugins:
  - jekyll-archives

pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  categories: true
  category_layout: 'blog'
  category_permalink: '/blog/category/:name/'
  sort_field: 'date'
  sort_reverse: true

jekyll-archives:
  enabled: ['categories']
  layout: 'blog'
  permalinks:
    category: '/blog/category/:name/'